export type FieldType = "text" | "tel" | "email" | "textarea" | "file" | "select" | "date";
export type DeliveryMode = "digital" | "physical";

export interface ServiceField {
  id: string;
  label: string;
  label_bn: string;
  type: FieldType;
  required: boolean;
  options?: string[];
  options_bn?: string[];
  helpText?: string;
}

export interface Service {
  slug: string;
  refPrefix: string;
  category: string;
  category_bn: string;
  name: string;
  name_bn: string;
  price: number;
  turnaround: string;
  turnaround_bn: string;
  summary: string;
  summary_bn: string;
  deliveryMode: DeliveryMode;
  fields: ServiceField[];
}

// Your original list had 68 numbered items. Many were duplicates or near
// duplicates of each other (e.g. "Job Application Submission" and
// "Government Job Application" are the same form). Below, every one of
// the 68 is covered — some as their own service, some consolidated into
// one form that asks which variant you need. See README for the mapping.

export const categories = [
  { en: "Printing & Document Services", bn: "প্রিন্টিং ও ডকুমেন্ট সেবা" },
  { en: "Online Application Services", bn: "অনলাইন আবেদন সেবা" },
  { en: "Government & Public Services", bn: "সরকারি ও জনসেবা" },
  { en: "Bills & Digital Payments", bn: "বিল ও ডিজিটাল পেমেন্ট" },
  { en: "Education Services", bn: "শিক্ষা সেবা" },
  { en: "Business & Office Services", bn: "ব্যবসা ও অফিস সেবা" },
  { en: "Other Digital Services", bn: "অন্যান্য ডিজিটাল সেবা" },
] as const;

// ── Reusable field groups, so 68 services don't mean 68 hand-built field
// lists. Each call returns a fresh array (nothing shared/mutated).

const notesField = (): ServiceField => ({
  id: "notes",
  label: "Anything we should know",
  label_bn: "অতিরিক্ত কিছু জানানোর থাকলে লিখুন",
  type: "textarea",
  required: false,
});

function physicalFields(docLabel: string, docLabel_bn: string, extra: ServiceField[] = []): ServiceField[] {
  return [
    { id: "document", label: docLabel, label_bn: docLabel_bn, type: "file", required: true },
    { id: "quantity", label: "Quantity / copies", label_bn: "সংখ্যা / কপি", type: "text", required: true },
    {
      id: "delivery_method",
      label: "Delivery method",
      label_bn: "ডেলিভারি পদ্ধতি",
      type: "select",
      required: true,
      options: ["Pickup from our counter", "Courier to my address (extra charge)"],
      options_bn: ["আমাদের কাউন্টার থেকে সংগ্রহ", "কুরিয়ারে আমার ঠিকানায় (অতিরিক্ত চার্জ)"],
    },
    { id: "address", label: "Delivery address (if courier)", label_bn: "ডেলিভারি ঠিকানা (কুরিয়ার হলে)", type: "textarea", required: false },
    ...extra,
    notesField(),
  ];
}

function applicationFields(subjectLabel: string, subjectLabel_bn: string, extra: ServiceField[] = []): ServiceField[] {
  return [
    { id: "subject", label: subjectLabel, label_bn: subjectLabel_bn, type: "text", required: true },
    { id: "documents", label: "Upload required documents", label_bn: "প্রয়োজনীয় কাগজপত্র আপলোড করুন", type: "file", required: true },
    ...extra,
    notesField(),
  ];
}

function infoLookupFields(idLabel: string, idLabel_bn: string): ServiceField[] {
  return [
    { id: "identifier", label: idLabel, label_bn: idLabel_bn, type: "text", required: true },
    { id: "full_name", label: "Full name (as on the document)", label_bn: "পূর্ণ নাম (ডকুমেন্টে যেভাবে আছে)", type: "text", required: true },
    notesField(),
  ];
}

function designFields(): ServiceField[] {
  return [
    { id: "requirements", label: "What do you want on it? (text, details)", label_bn: "কী কী তথ্য থাকবে বিস্তারিত লিখুন", type: "textarea", required: true },
    { id: "reference", label: "Upload a reference/logo/photo (optional)", label_bn: "রেফারেন্স/লোগো/ছবি আপলোড করুন (ঐচ্ছিক)", type: "file", required: false },
    { id: "size", label: "Size needed", label_bn: "প্রয়োজনীয় সাইজ", type: "text", required: false },
    notesField(),
  ];
}

export const services: Service[] = [
  // ══ Printing & Document Services (physical — pickup or courier) ══
  {
    slug: "birth-cert-printing",
    refPrefix: "BCP",
    category: "Printing & Document Services",
    category_bn: "প্রিন্টিং ও ডকুমেন্ট সেবা",
    name: "Birth Registration Certificate Printing",
    name_bn: "জন্মনিবন্ধন সনদ প্রিন্টিং",
    price: 30,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "We print your birth registration certificate from the official copy or PDF you provide.",
    summary_bn: "আপনার দেওয়া অফিসিয়াল কপি বা পিডিএফ থেকে জন্মনিবন্ধন সনদ প্রিন্ট করে দেওয়া হবে।",
    deliveryMode: "physical",
    fields: physicalFields("Upload the certificate PDF/photo", "সনদের পিডিএফ/ছবি আপলোড করুন"),
  },
  {
    slug: "certificate-document-printing",
    refPrefix: "CDP",
    category: "Printing & Document Services",
    category_bn: "প্রিন্টিং ও ডকুমেন্ট সেবা",
    name: "Certificate & Document Printing",
    name_bn: "সার্টিফিকেট ও ডকুমেন্ট প্রিন্টিং",
    price: 20,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "Any certificate, marksheet, admit card, or result printed clean and ready to submit.",
    summary_bn: "যেকোনো সার্টিফিকেট, মার্কশিট, অ্যাডমিট কার্ড বা রেজাল্ট পরিষ্কারভাবে প্রিন্ট করে দেওয়া হবে।",
    deliveryMode: "physical",
    fields: physicalFields("Upload the file to print", "প্রিন্ট করার ফাইল আপলোড করুন"),
  },
  {
    slug: "pdf-printing",
    refPrefix: "PDP",
    category: "Printing & Document Services",
    category_bn: "প্রিন্টিং ও ডকুমেন্ট সেবা",
    name: "PDF Printing",
    name_bn: "পিডিএফ প্রিন্টিং",
    price: 5,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "Any PDF file printed. Priced per page.",
    summary_bn: "যেকোনো পিডিএফ ফাইল প্রিন্ট করা হয়। প্রতি পাতা হিসেবে মূল্য।",
    deliveryMode: "physical",
    fields: physicalFields("Upload the PDF", "পিডিএফ আপলোড করুন"),
  },
  {
    slug: "photocopy",
    refPrefix: "PHC",
    category: "Printing & Document Services",
    category_bn: "প্রিন্টিং ও ডকুমেন্ট সেবা",
    name: "Photocopy Services",
    name_bn: "ফটোকপি সেবা",
    price: 2,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "Send us a photo/scan of the document and tell us how many copies you need.",
    summary_bn: "ডকুমেন্টের ছবি/স্ক্যান পাঠান এবং কতগুলো কপি লাগবে জানান।",
    deliveryMode: "physical",
    fields: physicalFields("Upload a photo/scan of the document", "ডকুমেন্টের ছবি/স্ক্যান আপলোড করুন"),
  },
  {
    slug: "document-scanning",
    refPrefix: "SCN",
    category: "Printing & Document Services",
    category_bn: "প্রিন্টিং ও ডকুমেন্ট সেবা",
    name: "Document Scanning",
    name_bn: "ডকুমেন্ট স্ক্যানিং",
    price: 10,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "Bring or courier your physical papers to us — we scan them into a clean PDF and send it back.",
    summary_bn: "আপনার কাগজপত্র আমাদের কাছে দিন — আমরা তা স্ক্যান করে পরিষ্কার পিডিএফ বানিয়ে ফেরত পাঠাব।",
    deliveryMode: "physical",
    fields: physicalFields("What are you sending? (describe)", "কী পাঠাচ্ছেন তা লিখুন", []),
  },
  {
    slug: "photo-printing",
    refPrefix: "PTP",
    category: "Printing & Document Services",
    category_bn: "প্রিন্টিং ও ডকুমেন্ট সেবা",
    name: "Photo Printing",
    name_bn: "ছবি প্রিন্টিং",
    price: 10,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "Regular photo prints in the size you need.",
    summary_bn: "আপনার প্রয়োজনীয় সাইজে সাধারণ ছবি প্রিন্ট করা হবে।",
    deliveryMode: "physical",
    fields: physicalFields("Upload the photo(s)", "ছবি আপলোড করুন", [
      { id: "size", label: "Print size (e.g. 4R, passport)", label_bn: "প্রিন্ট সাইজ (যেমন 4R, পাসপোর্ট)", type: "text", required: true },
    ]),
  },
  {
    slug: "passport-photo-print",
    refPrefix: "PPP",
    category: "Printing & Document Services",
    category_bn: "প্রিন্টিং ও ডকুমেন্ট সেবা",
    name: "Passport-Size Photo (edited + printed)",
    name_bn: "পাসপোর্ট সাইজ ছবি (এডিট ও প্রিন্ট)",
    price: 30,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "We edit your photo to passport/visa spec and print physical copies.",
    summary_bn: "আপনার ছবি পাসপোর্ট/ভিসা মানে এডিট করে ফিজিক্যাল কপি প্রিন্ট করে দেওয়া হবে।",
    deliveryMode: "physical",
    fields: physicalFields("Upload your photo", "আপনার ছবি আপলোড করুন", [
      { id: "spec", label: "Required size (e.g. passport, visa)", label_bn: "প্রয়োজনীয় সাইজ (যেমন পাসপোর্ট, ভিসা)", type: "text", required: true },
    ]),
  },
  {
    slug: "document-lamination",
    refPrefix: "LAM",
    category: "Printing & Document Services",
    category_bn: "প্রিন্টিং ও ডকুমেন্ট সেবা",
    name: "Document Lamination",
    name_bn: "ডকুমেন্ট লেমিনেশন",
    price: 20,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "Bring your document (or a printed copy we made for you) and we'll laminate it.",
    summary_bn: "আপনার ডকুমেন্ট (বা আমাদের প্রিন্ট করা কপি) নিয়ে এলে আমরা লেমিনেট করে দেব।",
    deliveryMode: "physical",
    fields: physicalFields("Describe what needs lamination", "কী লেমিনেট করতে হবে লিখুন"),
  },
  {
    slug: "document-binding",
    refPrefix: "BND",
    category: "Printing & Document Services",
    category_bn: "প্রিন্টিং ও ডকুমেন্ট সেবা",
    name: "Spiral / Document Binding",
    name_bn: "স্পাইরাল / ডকুমেন্ট বাইন্ডিং",
    price: 40,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "Multi-page documents (thesis, reports, assignments) bound and finished.",
    summary_bn: "একাধিক পাতার ডকুমেন্ট (থিসিস, রিপোর্ট, অ্যাসাইনমেন্ট) বাইন্ডিং করে দেওয়া হবে।",
    deliveryMode: "physical",
    fields: physicalFields("Upload the file to print & bind", "প্রিন্ট ও বাইন্ডিংয়ের ফাইল আপলোড করুন", [
      { id: "pages", label: "Approx. page count", label_bn: "আনুমানিক পাতার সংখ্যা", type: "text", required: true },
    ]),
  },

  // ══ Online Application Services (digital) ══
  {
    slug: "job-application",
    refPrefix: "JOB",
    category: "Online Application Services",
    category_bn: "অনলাইন আবেদন সেবা",
    name: "Job Application (Govt. or Private)",
    name_bn: "চাকরির আবেদন (সরকারি বা বেসরকারি)",
    price: 150,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "We fill and submit the application form for a specific post using your documents.",
    summary_bn: "আপনার কাগজপত্র দিয়ে নির্দিষ্ট পদের আবেদন ফর্ম পূরণ ও জমা দেওয়া হবে।",
    deliveryMode: "digital",
    fields: [
      { id: "post_name", label: "Post / job circular name", label_bn: "পদের নাম / সার্কুলার", type: "text", required: true },
      { id: "circular_link", label: "Link to the job circular (if any)", label_bn: "সার্কুলারের লিংক (যদি থাকে)", type: "text", required: false },
      { id: "nid_copy", label: "Upload NID copy", label_bn: "এনআইডি কপি আপলোড করুন", type: "file", required: true },
      { id: "photo", label: "Upload passport-size photo", label_bn: "পাসপোর্ট সাইজ ছবি আপলোড করুন", type: "file", required: true },
      { id: "signature", label: "Upload signature", label_bn: "স্বাক্ষর আপলোড করুন", type: "file", required: true },
      { id: "cert_copies", label: "Upload certificates", label_bn: "সার্টিফিকেট আপলোড করুন", type: "file", required: false },
      notesField(),
    ],
  },
  {
    slug: "admission-application",
    refPrefix: "ADM",
    category: "Online Application Services",
    category_bn: "অনলাইন আবেদন সেবা",
    name: "Admission Form (University / College / School / Madrasa)",
    name_bn: "ভর্তির ফর্ম (বিশ্ববিদ্যালয় / কলেজ / স্কুল / মাদ্রাসা)",
    price: 200,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "Admission form fill-up and submission for the institution of your choice, any level.",
    summary_bn: "যেকোনো স্তরের প্রতিষ্ঠানের ভর্তি ফর্ম পূরণ ও জমা দেওয়া হবে।",
    deliveryMode: "digital",
    fields: [
      { id: "institution", label: "Institution & program/class name", label_bn: "প্রতিষ্ঠান ও প্রোগ্রাম/শ্রেণির নাম", type: "text", required: true },
      { id: "prior_result", label: "Upload previous result/marksheet", label_bn: "পূর্বের ফলাফল/মার্কশিট আপলোড করুন", type: "file", required: true },
      { id: "nid_or_birth_cert", label: "Upload NID / Birth Registration", label_bn: "এনআইডি / জন্মনিবন্ধন আপলোড করুন", type: "file", required: true },
      { id: "photo", label: "Upload passport-size photo", label_bn: "পাসপোর্ট সাইজ ছবি আপলোড করুন", type: "file", required: true },
      notesField(),
    ],
  },
  {
    slug: "exam-registration",
    refPrefix: "EXM",
    category: "Online Application Services",
    category_bn: "অনলাইন আবেদন সেবা",
    name: "Examination Form Fill-up / Registration",
    name_bn: "পরীক্ষার ফর্ম পূরণ / রেজিস্ট্রেশন",
    price: 150,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "Board or institutional exam registration completed on your behalf.",
    summary_bn: "বোর্ড বা প্রতিষ্ঠানের পরীক্ষার রেজিস্ট্রেশন আপনার পক্ষে সম্পন্ন করা হবে।",
    deliveryMode: "digital",
    fields: applicationFields("Exam / board name", "পরীক্ষা / বোর্ডের নাম", [
      { id: "roll_reg", label: "Roll / Registration number (if any)", label_bn: "রোল / রেজিস্ট্রেশন নম্বর (যদি থাকে)", type: "text", required: false },
    ]),
  },
  {
    slug: "admit-result-download",
    refPrefix: "ADC",
    category: "Online Application Services",
    category_bn: "অনলাইন আবেদন সেবা",
    name: "Admit Card / Result Download",
    name_bn: "অ্যাডমিট কার্ড / রেজাল্ট ডাউনলোড",
    price: 50,
    turnaround: "Within hours",
    turnaround_bn: "কয়েক ঘণ্টার মধ্যে",
    summary: "We locate, download, and email you a clean digital copy. Want it printed too? Add the printing service separately.",
    summary_bn: "আমরা খুঁজে ডাউনলোড করে ইমেইলে পাঠিয়ে দেব। প্রিন্ট কপিও লাগলে আলাদাভাবে প্রিন্টিং সেবা নিন।",
    deliveryMode: "digital",
    fields: infoLookupFields("Roll & Registration number", "রোল ও রেজিস্ট্রেশন নম্বর"),
  },
  {
    slug: "scholarship-application",
    refPrefix: "SCH",
    category: "Online Application Services",
    category_bn: "অনলাইন আবেদন সেবা",
    name: "Scholarship Application",
    name_bn: "বৃত্তির আবেদন",
    price: 200,
    turnaround: "1–2 days",
    turnaround_bn: "১-২ দিন",
    summary: "We prepare and submit your scholarship application with supporting documents.",
    summary_bn: "সহায়ক কাগজপত্রসহ বৃত্তির আবেদন প্রস্তুত ও জমা দেওয়া হবে।",
    deliveryMode: "digital",
    fields: applicationFields("Scholarship name / program", "বৃত্তির নাম / প্রোগ্রাম"),
  },
  {
    slug: "misc-govt-application",
    refPrefix: "GOV",
    category: "Online Application Services",
    category_bn: "অনলাইন আবেদন সেবা",
    name: "Other Government Online Application",
    name_bn: "অন্যান্য সরকারি অনলাইন আবেদন",
    price: 150,
    turnaround: "1–2 days",
    turnaround_bn: "১-২ দিন",
    summary: "Don't see your specific government form above? Describe it and we'll submit it for you.",
    summary_bn: "আপনার নির্দিষ্ট সরকারি ফর্ম উপরে না পেলে বিস্তারিত লিখুন, আমরা জমা দেব।",
    deliveryMode: "digital",
    fields: applicationFields("Which application / which office", "কোন আবেদন / কোন অফিস"),
  },

  // ══ Government & Public Services (digital application; some require an
  //    office visit that we don't cover — we're upfront about that in the summary) ══
  {
    slug: "birth-reg-verification",
    refPrefix: "BRV",
    category: "Government & Public Services",
    category_bn: "সরকারি ও জনসেবা",
    name: "Birth Registration Verification & Download",
    name_bn: "জন্মনিবন্ধন যাচাই ও ডাউনলোড",
    price: 30,
    turnaround: "Within hours",
    turnaround_bn: "কয়েক ঘণ্টার মধ্যে",
    summary: "We verify your birth registration record online and send you a downloaded copy.",
    summary_bn: "আমরা অনলাইনে আপনার জন্মনিবন্ধন যাচাই করে ডাউনলোড কপি পাঠিয়ে দেব।",
    deliveryMode: "digital",
    fields: infoLookupFields("Birth Registration number", "জন্মনিবন্ধন নম্বর"),
  },
  {
    slug: "birth-correction-application",
    refPrefix: "BRC",
    category: "Government & Public Services",
    category_bn: "সরকারি ও জনসেবা",
    name: "Birth Registration Correction",
    name_bn: "জন্মনিবন্ধন সংশোধন",
    price: 300,
    turnaround: "1–2 days",
    turnaround_bn: "১-২ দিন",
    summary: "We prepare and submit the online correction request. An office visit, if the authority requires one, is not included.",
    summary_bn: "আমরা অনলাইন সংশোধনের আবেদন প্রস্তুত ও জমা দেব। অফিসে সশরীরে যাওয়ার প্রয়োজন হলে তা এর অন্তর্ভুক্ত নয়।",
    deliveryMode: "digital",
    fields: [
      { id: "brc_number", label: "Birth Registration number", label_bn: "জন্মনিবন্ধন নম্বর", type: "text", required: true },
      { id: "what_to_correct", label: "What needs to be corrected", label_bn: "কী সংশোধন করতে হবে লিখুন", type: "textarea", required: true },
      { id: "supporting_docs", label: "Upload supporting documents", label_bn: "সহায়ক কাগজপত্র আপলোড করুন", type: "file", required: true },
    ],
  },
  {
    slug: "death-registration-assistance",
    refPrefix: "DTH",
    category: "Government & Public Services",
    category_bn: "সরকারি ও জনসেবা",
    name: "Death Registration Assistance",
    name_bn: "মৃত্যু নিবন্ধন সহায়তা",
    price: 250,
    turnaround: "1–2 days",
    turnaround_bn: "১-২ দিন",
    summary: "We prepare and submit the death registration application online. Office visits are not included.",
    summary_bn: "আমরা অনলাইনে মৃত্যু নিবন্ধনের আবেদন প্রস্তুত ও জমা দেব। অফিসে সশরীরে যাওয়া এর অন্তর্ভুক্ত নয়।",
    deliveryMode: "digital",
    fields: applicationFields("Deceased's full name & NID (if available)", "মৃত ব্যক্তির নাম ও এনআইডি (যদি থাকে)"),
  },
  {
    slug: "nid-download-print",
    refPrefix: "NID",
    category: "Government & Public Services",
    category_bn: "সরকারি ও জনসেবা",
    name: "NID Download, Printing & Photocopy",
    name_bn: "এনআইডি ডাউনলোড, প্রিন্ট ও ফটোকপি",
    price: 30,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "We download your NID and can print or photocopy it — choose below.",
    summary_bn: "আমরা আপনার এনআইডি ডাউনলোড করে প্রিন্ট বা ফটোকপি করে দিতে পারি — নিচে বেছে নিন।",
    deliveryMode: "physical",
    fields: physicalFields("Upload NID number / slip / old copy", "এনআইডি নম্বর / স্লিপ / পুরনো কপি আপলোড করুন", [
      { id: "what_you_need", label: "What do you need?", label_bn: "কী প্রয়োজন?", type: "select", required: true, options: ["Digital download only", "Printed copy", "Photocopy"], options_bn: ["শুধু ডিজিটাল ডাউনলোড", "প্রিন্ট কপি", "ফটোকপি"] },
    ]),
  },
  {
    slug: "nid-correction-application",
    refPrefix: "NDC",
    category: "Government & Public Services",
    category_bn: "সরকারি ও জনসেবা",
    name: "NID Correction Application",
    name_bn: "এনআইডি সংশোধন আবেদন",
    price: 300,
    turnaround: "1–2 days",
    turnaround_bn: "১-২ দিন",
    summary: "We prepare and submit your NID correction request online. Office visits, if required, are not included.",
    summary_bn: "আমরা অনলাইনে এনআইডি সংশোধনের আবেদন প্রস্তুত ও জমা দেব। অফিসে যাওয়ার প্রয়োজন হলে তা অন্তর্ভুক্ত নয়।",
    deliveryMode: "digital",
    fields: [
      { id: "nid_number", label: "NID number", label_bn: "এনআইডি নম্বর", type: "text", required: true },
      { id: "what_to_correct", label: "What needs to be corrected", label_bn: "কী সংশোধন করতে হবে লিখুন", type: "textarea", required: true },
      { id: "supporting_docs", label: "Upload supporting documents", label_bn: "সহায়ক কাগজপত্র আপলোড করুন", type: "file", required: true },
    ],
  },
  {
    slug: "voter-info-verification",
    refPrefix: "VOT",
    category: "Government & Public Services",
    category_bn: "সরকারি ও জনসেবা",
    name: "Voter Information Verification",
    name_bn: "ভোটার তথ্য যাচাই",
    price: 20,
    turnaround: "Within hours",
    turnaround_bn: "কয়েক ঘণ্টার মধ্যে",
    summary: "We check your voter registration details and send you a confirmation.",
    summary_bn: "আমরা আপনার ভোটার নিবন্ধনের তথ্য যাচাই করে নিশ্চিতকরণ পাঠিয়ে দেব।",
    deliveryMode: "digital",
    fields: infoLookupFields("NID or Voter number", "এনআইডি বা ভোটার নম্বর"),
  },
  {
    slug: "citizenship-certificate",
    refPrefix: "CTZ",
    category: "Government & Public Services",
    category_bn: "সরকারি ও জনসেবা",
    name: "Citizenship / Other Certificate Application",
    name_bn: "নাগরিকত্ব / অন্যান্য সনদের আবেদন",
    price: 250,
    turnaround: "1–2 days",
    turnaround_bn: "১-২ দিন",
    summary: "We prepare and submit the application for a citizenship or similar certificate.",
    summary_bn: "আমরা নাগরিকত্ব বা অনুরূপ সনদের আবেদন প্রস্তুত ও জমা দেব।",
    deliveryMode: "digital",
    fields: applicationFields("Which certificate do you need?", "কোন সনদ প্রয়োজন?"),
  },
  {
    slug: "passport-application-assistance",
    refPrefix: "PSP",
    category: "Government & Public Services",
    category_bn: "সরকারি ও জনসেবা",
    name: "Passport Application Assistance",
    name_bn: "পাসপোর্ট আবেদন সহায়তা",
    price: 300,
    turnaround: "1–2 days",
    turnaround_bn: "১-২ দিন",
    summary: "We fill and submit your online passport application (e-passport). Biometric enrollment at a passport office is not included and must be done in person.",
    summary_bn: "আমরা আপনার অনলাইন পাসপোর্ট আবেদন (ই-পাসপোর্ট) পূরণ ও জমা দেব। বায়োমেট্রিক নিবন্ধন পাসপোর্ট অফিসে সশরীরে করতে হবে, এটি এর অন্তর্ভুক্ত নয়।",
    deliveryMode: "digital",
    fields: applicationFields("Application type (new / renewal / etc.)", "আবেদনের ধরন (নতুন / নবায়ন ইত্যাদি)"),
  },
  {
    slug: "police-clearance-application",
    refPrefix: "PCC",
    category: "Government & Public Services",
    category_bn: "সরকারি ও জনসেবা",
    name: "Police Clearance Certificate Application",
    name_bn: "পুলিশ ক্লিয়ারেন্স সার্টিফিকেট আবেদন",
    price: 300,
    turnaround: "1–2 days",
    turnaround_bn: "১-২ দিন",
    summary: "We fill and submit your online PCC application.",
    summary_bn: "আমরা আপনার অনলাইন পিসিসি আবেদন পূরণ ও জমা দেব।",
    deliveryMode: "digital",
    fields: applicationFields("Purpose (visa, job abroad, etc.)", "উদ্দেশ্য (ভিসা, বিদেশে চাকরি ইত্যাদি)"),
  },
  {
    slug: "govt-fees-challan-payment",
    refPrefix: "CHL",
    category: "Government & Public Services",
    category_bn: "সরকারি ও জনসেবা",
    name: "Government Fee / Challan Payment",
    name_bn: "সরকারি ফি / চালান পরিশোধ",
    price: 30,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "We pay a government fee or e-challan on your behalf. Flat service charge on top of the fee amount.",
    summary_bn: "আমরা আপনার পক্ষে সরকারি ফি বা ই-চালান পরিশোধ করে দেব। ফি-এর সাথে নির্দিষ্ট সার্ভিস চার্জ যোগ হবে।",
    deliveryMode: "digital",
    fields: [
      { id: "purpose", label: "What is this fee for?", label_bn: "এই ফি কীসের জন্য?", type: "text", required: true },
      { id: "challan_details", label: "Challan/reference number or slip", label_bn: "চালান/রেফারেন্স নম্বর বা স্লিপ", type: "text", required: true },
      { id: "amount", label: "Fee amount (BDT)", label_bn: "ফি-এর পরিমাণ (টাকা)", type: "text", required: true },
    ],
  },

  // ══ Bills & Digital Payments ══
  {
    slug: "mobile-recharge",
    refPrefix: "RCH",
    category: "Bills & Digital Payments",
    category_bn: "বিল ও ডিজিটাল পেমেন্ট",
    name: "Mobile Recharge",
    name_bn: "মোবাইল রিচার্জ",
    price: 5,
    turnaround: "Instant",
    turnaround_bn: "তাৎক্ষণিক",
    summary: "Top up any Bangladeshi mobile number. Flat service charge on top of the recharge amount.",
    summary_bn: "যেকোনো বাংলাদেশি মোবাইল নম্বরে রিচার্জ করা হয়। রিচার্জের অর্থের সাথে নির্দিষ্ট সার্ভিস চার্জ যোগ হবে।",
    deliveryMode: "digital",
    fields: [
      { id: "number", label: "Mobile number", label_bn: "মোবাইল নম্বর", type: "tel", required: true },
      { id: "operator", label: "Operator", label_bn: "অপারেটর", type: "select", required: true, options: ["Grameenphone", "Robi", "Banglalink", "Airtel", "Teletalk"], options_bn: ["গ্রামীণফোন", "রবি", "বাংলালিংক", "এয়ারটেল", "টেলিটক"] },
      { id: "amount", label: "Recharge amount (BDT)", label_bn: "রিচার্জের পরিমাণ (টাকা)", type: "text", required: true },
    ],
  },
  {
    slug: "electricity-bill",
    refPrefix: "ELB",
    category: "Bills & Digital Payments",
    category_bn: "বিল ও ডিজিটাল পেমেন্ট",
    name: "Electricity Bill Payment",
    name_bn: "বিদ্যুৎ বিল পরিশোধ",
    price: 20,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "We pay your electricity bill on time. Flat service charge on top of the bill amount.",
    summary_bn: "আমরা সময়মতো আপনার বিদ্যুৎ বিল পরিশোধ করে দেব। বিলের সাথে নির্দিষ্ট সার্ভিস চার্জ যোগ হবে।",
    deliveryMode: "digital",
    fields: [
      { id: "account_no", label: "Account / SMS number", label_bn: "অ্যাকাউন্ট / এসএমএস নম্বর", type: "text", required: true },
      { id: "provider", label: "Provider (DESCO/DPDC/PBS/etc.)", label_bn: "প্রোভাইডার (ডেসকো/ডিপিডিসি/পিবিএস ইত্যাদি)", type: "text", required: true },
      { id: "bill_copy", label: "Upload bill copy (optional)", label_bn: "বিলের কপি আপলোড করুন (ঐচ্ছিক)", type: "file", required: false },
    ],
  },
  {
    slug: "internet-gas-water-bill",
    refPrefix: "NTB",
    category: "Bills & Digital Payments",
    category_bn: "বিল ও ডিজিটাল পেমেন্ট",
    name: "Internet / Gas / Water Bill Payment",
    name_bn: "ইন্টারনেট / গ্যাস / পানি বিল পরিশোধ",
    price: 20,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "We pay your utility bill on time. Flat service charge on top of the bill amount.",
    summary_bn: "আমরা সময়মতো আপনার ইউটিলিটি বিল পরিশোধ করে দেব। বিলের সাথে নির্দিষ্ট সার্ভিস চার্জ যোগ হবে।",
    deliveryMode: "digital",
    fields: [
      { id: "bill_type", label: "Bill type", label_bn: "বিলের ধরন", type: "select", required: true, options: ["Internet", "Gas", "Water"], options_bn: ["ইন্টারনেট", "গ্যাস", "পানি"] },
      { id: "account_no", label: "Account / customer number", label_bn: "অ্যাকাউন্ট / গ্রাহক নম্বর", type: "text", required: true },
      { id: "bill_copy", label: "Upload bill copy (optional)", label_bn: "বিলের কপি আপলোড করুন (ঐচ্ছিক)", type: "file", required: false },
    ],
  },
  {
    slug: "online-payment-assistance",
    refPrefix: "PAY",
    category: "Bills & Digital Payments",
    category_bn: "বিল ও ডিজিটাল পেমেন্ট",
    name: "Online Payment Assistance",
    name_bn: "অনলাইন পেমেন্ট সহায়তা",
    price: 20,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "Need to pay for something online but don't have a card or trust the site? Tell us and we'll pay it for you.",
    summary_bn: "অনলাইনে কিছু পরিশোধ করতে হবে কিন্তু কার্ড নেই বা সাইট বিশ্বাস করতে পারছেন না? আমাদের জানান, আমরা পরিশোধ করে দেব।",
    deliveryMode: "digital",
    fields: [
      { id: "what_to_pay", label: "What are you paying for?", label_bn: "কীসের জন্য পরিশোধ করছেন?", type: "text", required: true },
      { id: "link", label: "Link/site (if any)", label_bn: "লিংক/সাইট (যদি থাকে)", type: "text", required: false },
      { id: "amount", label: "Amount (BDT)", label_bn: "পরিমাণ (টাকা)", type: "text", required: true },
    ],
  },
  {
    slug: "institution-fee-payment",
    refPrefix: "IFP",
    category: "Bills & Digital Payments",
    category_bn: "বিল ও ডিজিটাল পেমেন্ট",
    name: "Educational Institution Fee Payment",
    name_bn: "শিক্ষা প্রতিষ্ঠানের ফি পরিশোধ",
    price: 30,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "Tuition, exam, or admission fees paid to your school/college/university on time.",
    summary_bn: "স্কুল/কলেজ/বিশ্ববিদ্যালয়ের টিউশন, পরীক্ষা বা ভর্তি ফি সময়মতো পরিশোধ করে দেওয়া হবে।",
    deliveryMode: "digital",
    fields: [
      { id: "institution", label: "Institution name", label_bn: "প্রতিষ্ঠানের নাম", type: "text", required: true },
      { id: "student_id", label: "Student ID / Roll", label_bn: "স্টুডেন্ট আইডি / রোল", type: "text", required: true },
      { id: "amount", label: "Amount (BDT)", label_bn: "পরিমাণ (টাকা)", type: "text", required: true },
    ],
  },

  // ══ Education Services ══
  {
    slug: "academic-document-printing",
    refPrefix: "ADP",
    category: "Education Services",
    category_bn: "শিক্ষা সেবা",
    name: "Marksheet & Registration Card Printing",
    name_bn: "মার্কশিট ও রেজিস্ট্রেশন কার্ড প্রিন্টিং",
    price: 20,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "Marksheets, registration cards, and similar academic documents printed clean.",
    summary_bn: "মার্কশিট, রেজিস্ট্রেশন কার্ড ও এ ধরনের একাডেমিক ডকুমেন্ট পরিষ্কারভাবে প্রিন্ট করে দেওয়া হবে।",
    deliveryMode: "physical",
    fields: physicalFields("Upload the file to print", "প্রিন্ট করার ফাইল আপলোড করুন"),
  },
  {
    slug: "education-board-services",
    refPrefix: "EBS",
    category: "Education Services",
    category_bn: "শিক্ষা সেবা",
    name: "Education Board Online Services",
    name_bn: "শিক্ষা বোর্ডের অনলাইন সেবা",
    price: 100,
    turnaround: "1–2 days",
    turnaround_bn: "১-২ দিন",
    summary: "Board-related online tasks — migration, verification requests, and similar — handled for you.",
    summary_bn: "মাইগ্রেশন, যাচাই আবেদনসহ বোর্ড-সংক্রান্ত অনলাইন কাজ আমরা করে দেব।",
    deliveryMode: "digital",
    fields: applicationFields("What board service do you need?", "কোন বোর্ড সেবা প্রয়োজন?"),
  },
  {
    slug: "study-material-printing",
    refPrefix: "STM",
    category: "Education Services",
    category_bn: "শিক্ষা সেবা",
    name: "Question Paper / Notes / Assignment Printing",
    name_bn: "প্রশ্নপত্র / নোট / অ্যাসাইনমেন্ট প্রিন্টিং",
    price: 5,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "Study notes, question papers, and assignments printed. Priced per page.",
    summary_bn: "স্টাডি নোট, প্রশ্নপত্র ও অ্যাসাইনমেন্ট প্রিন্ট করা হয়। প্রতি পাতা হিসেবে মূল্য।",
    deliveryMode: "physical",
    fields: physicalFields("Upload the file(s) to print", "প্রিন্ট করার ফাইল আপলোড করুন"),
  },

  // ══ Documents & Editing (typing, CV, conversions, photo editing) ══
  {
    slug: "cv-resume",
    refPrefix: "CVR",
    category: "Business & Office Services",
    category_bn: "ব্যবসা ও অফিস সেবা",
    name: "CV / Resume Creation",
    name_bn: "সিভি / জীবনবৃত্তান্ত তৈরি",
    price: 250,
    turnaround: "1 day",
    turnaround_bn: "১ দিন",
    summary: "A clean, print-ready CV built from your details, delivered as PDF + editable file.",
    summary_bn: "আপনার তথ্য দিয়ে পরিষ্কার, প্রিন্ট-উপযোগী সিভি তৈরি করে PDF ও এডিটযোগ্য ফাইল দেওয়া হবে।",
    deliveryMode: "digital",
    fields: [
      { id: "full_details", label: "Your details (education, experience, skills)", label_bn: "আপনার তথ্য (শিক্ষা, অভিজ্ঞতা, দক্ষতা)", type: "textarea", required: true },
      { id: "photo", label: "Upload photo (optional)", label_bn: "ছবি আপলোড করুন (ঐচ্ছিক)", type: "file", required: false },
      { id: "target_role", label: "Target role / industry (optional)", label_bn: "লক্ষ্য পদ / খাত (ঐচ্ছিক)", type: "text", required: false },
    ],
  },
  {
    slug: "application-letter",
    refPrefix: "APL",
    category: "Business & Office Services",
    category_bn: "ব্যবসা ও অফিস সেবা",
    name: "Application / Letter Writing & Typing",
    name_bn: "আবেদনপত্র / চিঠি লেখা ও টাইপিং",
    price: 100,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "A formally worded, properly formatted application or letter, typed and delivered as PDF.",
    summary_bn: "সঠিক ভাষা ও ফরম্যাটে আবেদনপত্র বা চিঠি টাইপ করে PDF আকারে দেওয়া হবে।",
    deliveryMode: "digital",
    fields: [
      { id: "purpose", label: "What is this application for?", label_bn: "আবেদনের উদ্দেশ্য কী?", type: "textarea", required: true },
      { id: "language", label: "Language", label_bn: "ভাষা", type: "select", required: true, options: ["Bangla", "English"], options_bn: ["বাংলা", "ইংরেজি"] },
    ],
  },
  {
    slug: "typing-composition",
    refPrefix: "TYP",
    category: "Business & Office Services",
    category_bn: "ব্যবসা ও অফিস সেবা",
    name: "Bangla / English Typing & Composition",
    name_bn: "বাংলা / ইংরেজি টাইপিং ও কম্পোজিশন",
    price: 5,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "Handwritten or scanned pages typed cleanly. Priced per page.",
    summary_bn: "হাতে লেখা বা স্ক্যান করা পাতা পরিষ্কারভাবে টাইপ করে দেওয়া হবে। প্রতি পাতা হিসেবে মূল্য।",
    deliveryMode: "digital",
    fields: [
      { id: "source_file", label: "Upload the pages to be typed", label_bn: "টাইপ করার পাতাগুলো আপলোড করুন", type: "file", required: true },
      { id: "page_count", label: "Number of pages", label_bn: "পাতার সংখ্যা", type: "text", required: true },
      { id: "language", label: "Language", label_bn: "ভাষা", type: "select", required: true, options: ["Bangla", "English", "Both"], options_bn: ["বাংলা", "ইংরেজি", "উভয়ই"] },
    ],
  },
  {
    slug: "file-format-conversion",
    refPrefix: "CNV",
    category: "Business & Office Services",
    category_bn: "ব্যবসা ও অফিস সেবা",
    name: "PDF ⇄ Word / Image ⇄ PDF Conversion",
    name_bn: "পিডিএফ ⇄ ওয়ার্ড / ছবি ⇄ পিডিএফ রূপান্তর",
    price: 30,
    turnaround: "Within hours",
    turnaround_bn: "কয়েক ঘণ্টার মধ্যে",
    summary: "Convert between PDF, Word, JPG and PNG. Priced per file.",
    summary_bn: "PDF, Word, JPG এবং PNG-এর মধ্যে রূপান্তর করা হয়। প্রতি ফাইল হিসেবে মূল্য।",
    deliveryMode: "digital",
    fields: [
      { id: "source_file", label: "Upload the file(s) to convert", label_bn: "রূপান্তরের জন্য ফাইল আপলোড করুন", type: "file", required: true },
      { id: "target_format", label: "Convert to", label_bn: "যে ফরম্যাটে রূপান্তর করতে হবে", type: "select", required: true, options: ["PDF", "Word", "JPG/PNG"], options_bn: ["পিডিএফ", "ওয়ার্ড", "জেপিজি/পিএনজি"] },
    ],
  },
  {
    slug: "photo-editing",
    refPrefix: "PHT",
    category: "Business & Office Services",
    category_bn: "ব্যবসা ও অফিস সেবা",
    name: "Photo Editing / Background Removal",
    name_bn: "ছবি এডিটিং / ব্যাকগ্রাউন্ড পরিবর্তন",
    price: 40,
    turnaround: "Within hours",
    turnaround_bn: "কয়েক ঘণ্টার মধ্যে",
    summary: "Passport/visa-standard photo editing and background changes from a photo you send us.",
    summary_bn: "পাসপোর্ট/ভিসা মানের ছবি এডিটিং ও ব্যাকগ্রাউন্ড পরিবর্তন করা হবে।",
    deliveryMode: "digital",
    fields: [
      { id: "photo", label: "Upload your photo", label_bn: "আপনার ছবি আপলোড করুন", type: "file", required: true },
      { id: "requirement", label: "What size/background is required?", label_bn: "কী সাইজ/ব্যাকগ্রাউন্ড প্রয়োজন?", type: "text", required: true },
    ],
  },
  {
    slug: "signature-photo-prep",
    refPrefix: "SIG",
    category: "Business & Office Services",
    category_bn: "ব্যবসা ও অফিস সেবা",
    name: "Online Form Photo & Signature Preparation",
    name_bn: "অনলাইন ফর্মের ছবি ও স্বাক্ষর প্রস্তুতি",
    price: 30,
    turnaround: "Within hours",
    turnaround_bn: "কয়েক ঘণ্টার মধ্যে",
    summary: "Resize and format your photo/signature to exact specs for a specific online form.",
    summary_bn: "নির্দিষ্ট অনলাইন ফর্মের জন্য আপনার ছবি/স্বাক্ষর সঠিক মাপে প্রস্তুত করে দেওয়া হবে।",
    deliveryMode: "digital",
    fields: [
      { id: "photo_or_sig", label: "Upload photo/signature", label_bn: "ছবি/স্বাক্ষর আপলোড করুন", type: "file", required: true },
      { id: "spec", label: "Required size/format", label_bn: "প্রয়োজনীয় সাইজ/ফরম্যাট", type: "text", required: true },
    ],
  },

  // ══ Business & Office Services ══
  {
    slug: "trade-license-application",
    refPrefix: "TLA",
    category: "Business & Office Services",
    category_bn: "ব্যবসা ও অফিস সেবা",
    name: "Trade License Online Application Assistance",
    name_bn: "ট্রেড লাইসেন্স অনলাইন আবেদন সহায়তা",
    price: 500,
    turnaround: "1–2 days",
    turnaround_bn: "১-২ দিন",
    summary: "We fill and submit your trade license application with the relevant city corporation portal.",
    summary_bn: "সিটি কর্পোরেশন পোর্টালে আপনার ট্রেড লাইসেন্স আবেদন পূরণ ও জমা দেওয়া হবে।",
    deliveryMode: "digital",
    fields: applicationFields("Business name & type", "ব্যবসার নাম ও ধরন"),
  },
  {
    slug: "business-document-prep",
    refPrefix: "BDP",
    category: "Business & Office Services",
    category_bn: "ব্যবসা ও অফিস সেবা",
    name: "Business Document Preparation",
    name_bn: "ব্যবসায়িক ডকুমেন্ট প্রস্তুতি",
    price: 200,
    turnaround: "1 day",
    turnaround_bn: "১ দিন",
    summary: "Partnership deeds, quotations, and other standard business documents drafted for you.",
    summary_bn: "পার্টনারশিপ দলিল, কোটেশন ও অন্যান্য প্রমিত ব্যবসায়িক ডকুমেন্ট তৈরি করে দেওয়া হবে।",
    deliveryMode: "digital",
    fields: [
      { id: "doc_type", label: "What document do you need?", label_bn: "কোন ডকুমেন্ট প্রয়োজন?", type: "text", required: true },
      { id: "details", label: "Details to include", label_bn: "যেসব তথ্য থাকবে", type: "textarea", required: true },
    ],
  },
  {
    slug: "invoice-creation",
    refPrefix: "INV",
    category: "Business & Office Services",
    category_bn: "ব্যবসা ও অফিস সেবা",
    name: "Invoice & Bill Creation",
    name_bn: "ইনভয়েস ও বিল তৈরি",
    price: 50,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "A clean, professional invoice made from your business and item details.",
    summary_bn: "আপনার ব্যবসা ও আইটেমের তথ্য দিয়ে পরিষ্কার, পেশাদার ইনভয়েস তৈরি করে দেওয়া হবে।",
    deliveryMode: "digital",
    fields: [
      { id: "business_name", label: "Your business name", label_bn: "আপনার ব্যবসার নাম", type: "text", required: true },
      { id: "items", label: "Items, quantities & prices", label_bn: "আইটেম, পরিমাণ ও মূল্য", type: "textarea", required: true },
      { id: "client_details", label: "Client name & address", label_bn: "ক্লায়েন্টের নাম ও ঠিকানা", type: "textarea", required: true },
    ],
  },
  {
    slug: "excel-accounting-service",
    refPrefix: "EXC",
    category: "Business & Office Services",
    category_bn: "ব্যবসা ও অফিস সেবা",
    name: "Excel-Based Accounting & Record Keeping",
    name_bn: "এক্সেল-ভিত্তিক হিসাবরক্ষণ",
    price: 300,
    turnaround: "1–2 days",
    turnaround_bn: "১-২ দিন",
    summary: "We build or update a simple Excel sheet to track your income, expenses, or inventory.",
    summary_bn: "আপনার আয়, ব্যয় বা মজুদ ট্র্যাক করার জন্য সহজ এক্সেল শিট তৈরি বা আপডেট করে দেওয়া হবে।",
    deliveryMode: "digital",
    fields: [
      { id: "what_to_track", label: "What do you want to track?", label_bn: "কী ট্র্যাক করতে চান?", type: "textarea", required: true },
      { id: "existing_file", label: "Upload existing data/sheet (optional)", label_bn: "বিদ্যমান ডেটা/শিট আপলোড করুন (ঐচ্ছিক)", type: "file", required: false },
    ],
  },
  {
    slug: "poster-banner-design",
    refPrefix: "PBD",
    category: "Business & Office Services",
    category_bn: "ব্যবসা ও অফিস সেবা",
    name: "Poster & Banner Design",
    name_bn: "পোস্টার ও ব্যানার ডিজাইন",
    price: 300,
    turnaround: "1 day",
    turnaround_bn: "১ দিন",
    summary: "A custom poster or banner designed to your specs, delivered as a print-ready file.",
    summary_bn: "আপনার প্রয়োজন অনুযায়ী পোস্টার বা ব্যানার ডিজাইন করে প্রিন্ট-রেডি ফাইল দেওয়া হবে।",
    deliveryMode: "digital",
    fields: designFields(),
  },
  {
    slug: "visiting-card-design",
    refPrefix: "VCD",
    category: "Business & Office Services",
    category_bn: "ব্যবসা ও অফিস সেবা",
    name: "Visiting Card Design",
    name_bn: "ভিজিটিং কার্ড ডিজাইন",
    price: 150,
    turnaround: "1 day",
    turnaround_bn: "১ দিন",
    summary: "A professional visiting card designed with your details, delivered print-ready.",
    summary_bn: "আপনার তথ্য দিয়ে পেশাদার ভিজিটিং কার্ড ডিজাইন করে প্রিন্ট-রেডি ফাইল দেওয়া হবে।",
    deliveryMode: "digital",
    fields: designFields(),
  },
  {
    slug: "menu-leaflet-design",
    refPrefix: "MLD",
    category: "Business & Office Services",
    category_bn: "ব্যবসা ও অফিস সেবা",
    name: "Menu & Leaflet Design",
    name_bn: "মেনু ও লিফলেট ডিজাইন",
    price: 300,
    turnaround: "1–2 days",
    turnaround_bn: "১-২ দিন",
    summary: "Restaurant menus, shop leaflets, and flyers designed and delivered print-ready.",
    summary_bn: "রেস্টুরেন্ট মেনু, দোকানের লিফলেট ও ফ্লায়ার ডিজাইন করে প্রিন্ট-রেডি ফাইল দেওয়া হবে।",
    deliveryMode: "digital",
    fields: designFields(),
  },

  // ══ Other Digital Services ══
  {
    slug: "email-account-assistance",
    refPrefix: "EML",
    category: "Other Digital Services",
    category_bn: "অন্যান্য ডিজিটাল সেবা",
    name: "Email / Gmail Account Setup Assistance",
    name_bn: "ইমেইল / জিমেইল অ্যাকাউন্ট তৈরির সহায়তা",
    price: 50,
    turnaround: "Within hours",
    turnaround_bn: "কয়েক ঘণ্টার মধ্যে",
    summary: "We guide you through creating a new email/Gmail account, or help recover access to an existing one.",
    summary_bn: "নতুন ইমেইল/জিমেইল অ্যাকাউন্ট তৈরি বা বিদ্যমান অ্যাকাউন্টের অ্যাক্সেস ফিরে পেতে সহায়তা করা হবে।",
    deliveryMode: "digital",
    fields: [
      { id: "task", label: "New account or recover existing?", label_bn: "নতুন অ্যাকাউন্ট নাকি পুরনো ফিরে পেতে হবে?", type: "select", required: true, options: ["New account", "Recover existing"], options_bn: ["নতুন অ্যাকাউন্ট", "পুরনো ফিরে পেতে চাই"] },
      { id: "preferred_name", label: "Preferred name for the account", label_bn: "অ্যাকাউন্টের জন্য পছন্দের নাম", type: "text", required: true },
    ],
  },
  {
    slug: "file-transfer-service",
    refPrefix: "FTR",
    category: "Other Digital Services",
    category_bn: "অন্যান্য ডিজিটাল সেবা",
    name: "File Transfer (Pen Drive / Memory Card)",
    name_bn: "ফাইল ট্রান্সফার (পেনড্রাইভ / মেমোরি কার্ড)",
    price: 30,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "Send us your pen drive/memory card (pickup or courier) and tell us what to move where.",
    summary_bn: "আপনার পেনড্রাইভ/মেমোরি কার্ড পাঠান (পিকআপ বা কুরিয়ার) এবং কী কোথায় স্থানান্তর করতে হবে জানান।",
    deliveryMode: "physical",
    fields: physicalFields("Describe what needs transferring", "কী স্থানান্তর করতে হবে লিখুন"),
  },
  {
    slug: "document-download-assistance",
    refPrefix: "DDA",
    category: "Other Digital Services",
    category_bn: "অন্যান্য ডিজিটাল সেবা",
    name: "Online Document Download Assistance",
    name_bn: "অনলাইন ডকুমেন্ট ডাউনলোড সহায়তা",
    price: 30,
    turnaround: "Within hours",
    turnaround_bn: "কয়েক ঘণ্টার মধ্যে",
    summary: "Any government/institutional portal document you're struggling to download — we get it and send it to you.",
    summary_bn: "যেকোনো সরকারি/প্রাতিষ্ঠানিক পোর্টাল থেকে ডাউনলোড করতে সমস্যা হলে, আমরা ডাউনলোড করে পাঠিয়ে দেব।",
    deliveryMode: "digital",
    fields: applicationFields("Which document, from which site?", "কোন ডকুমেন্ট, কোন সাইট থেকে?"),
  },
  {
    slug: "ticket-booking-assistance",
    refPrefix: "TKT",
    category: "Other Digital Services",
    category_bn: "অন্যান্য ডিজিটাল সেবা",
    name: "Ticket / Booking Assistance",
    name_bn: "টিকেট / বুকিং সহায়তা",
    price: 30,
    turnaround: "Same day",
    turnaround_bn: "একই দিনে",
    summary: "Bus, train, or event ticket booking and printing assistance.",
    summary_bn: "বাস, ট্রেন বা ইভেন্ট টিকেট বুকিং ও প্রিন্টিংয়ে সহায়তা।",
    deliveryMode: "digital",
    fields: [
      { id: "booking_type", label: "What are you booking?", label_bn: "কী বুকিং করতে চান?", type: "text", required: true },
      { id: "details", label: "Route/date/details", label_bn: "রুট/তারিখ/বিস্তারিত", type: "textarea", required: true },
    ],
  },
];

export function getServiceBySlug(slug: string) {
  return services.find((s) => s.slug === slug);
}

export function groupByCategory() {
  return categories.map((cat) => ({
    category: cat.en,
    category_bn: cat.bn,
    items: services.filter((s) => s.category === cat.en),
  }));
}
